[workspace]
authors = ["drwho495 <drwho495555@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "ConstraintDesignMojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.6.0.dev2025080405,<26"
